# Generated by Django 2.2 on 2019-04-17 19:54

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NcPIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='PIO First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='PIO Last Name')),
                ('middle_name', models.CharField(max_length=20, verbose_name='PIO Middle Name or Initial')),
                ('email', models.EmailField(max_length=50, verbose_name='PIO Office Email')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'", regex='^\\d{10}$')], verbose_name='PIO Phone Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NcSheriff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Sheriff First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Sheriff Last Name')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Sheriff Middle Name or Initial')),
                ('office_email', models.EmailField(max_length=50, verbose_name='Sheriff Office Email')),
                ('office_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'", regex='^\\d{10}$')], verbose_name='Sheriff Office Phone Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NcJail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jail Name')),
                ('city', models.CharField(max_length=20, verbose_name='Jail City')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'", regex='^\\d{10}$')], verbose_name='Main Jail Phone Number')),
                ('search_url', models.URLField(verbose_name='Inmate Search URL')),
                ('opened_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message="Year must be entered in the format: '2222'", regex='^\\d{4}$')], verbose_name='Year of Jail Opening')),
                ('renovated_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message="Year must be entered in the format: '2222'", regex='^\\d{4}$')], verbose_name='Year of Most Recent Renovations')),
                ('daily_pop', models.PositiveIntegerField(verbose_name='Average Daily Population')),
                ('staff', models.PositiveIntegerField(verbose_name='Number of Staff')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1, verbose_name='Genders in Prison')),
                ('loc_pop_den', models.CharField(choices=[('MR', 'Mostly Rural'), ('CR', 'Completely Rural'), ('MU', 'Mostly Urban'), ('CU', 'Completely Urban')], max_length=2, verbose_name='Census Information on Location of Prison Urban vs Rural')),
                ('address', models.CharField(max_length=255, verbose_name='Jail Address')),
                ('budget', models.PositiveIntegerField(verbose_name='Budget')),
                ('email', models.EmailField(max_length=254, verbose_name='Jail Office Email')),
                ('pio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nc.NcPIO')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NcCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='County Name')),
                ('fips', models.CharField(max_length=3, verbose_name='FIPS Code')),
                ('border', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='County Border for Mapping')),
                ('jails', models.ManyToManyField(to='nc.NcJail')),
                ('sheriff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nc.NcSheriff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
